### ISSUE TITLE
Intermittent keyboard input

### ISSUE THREAD

**Issue by scottalmond** [tipam/pi3d#222]
On every frame of a pi3d project I call keys.read().  I find that on roughly every-other-frame I get a -1 response from keys.read(), even when holding a key down.  My current workaround is to take the maximum of the current key pressed and the key pressed in the previous frame to smooth over the -1 jitter.  For example, if I hold down 'a', I'll get a reading from keys.read() every frame that when concatenated looks like: [-1, ord('a'), -1, ord('a'), -1 ...].  But if I take the maximum of sequential frames I get: [-1, ord('a'), ord('a'), ord('a'), ord('a') ... ]

Demo code:
Set 'is_smooth_motion_enabled' to True/False and then use WASD in the following code.  When False, there is notable jitter in the scene as the SceneManager is trying to alternately update the state with no user input and with some user input.  When True, the averaging smooths the keys.read() output into a continuous stream.
https://github.com/scottalmond/EscapeRoom/blob/master/testing/SceneManager.py

**Comment by paddywwoof** [comment]
hmm. I think this is because of the way the keyboards are set to operate. ie holding down produce a series of char at a specific rate, probably slower than your frame rate. What you need is a lower level operation to look at key state at any moment, or else keep track of depression and releases. If you're using the pi then the event system might do this (see Silo demo)
