### ISSUE TITLE
Name only shows for 1 second, and disappears.

### ISSUE THREAD

**Issue by Ascendin81** [tipam/pi3d#245]
Hello, I have pi3d running as a picture frame slideshow.  The database has over 100,000 photos, categorized by date in their name, and usually takes 5 hours to load via WiFi.

I enabled "show names", but I can not get the name to STICK for the entire life of the photo.  Can you please create the ability for us to show to show the name on TOP or SIDE of photo in a black bar with white text, so I can see when the photo was taken?

Thank you!

**Comment by paddywwoof** [comment]
Hi, that's not too difficult to do but I appreciate it might be a tall order to become familiar with python then figure out how all the components of pi3d work!

The first thing I would suggest is that you copy a small  number of images to a folder then set your PIC_DIR to that to speed up the process of tweaking things the way you want them.

To stop the text fading you need to comment out the place where the alpha is gradually reduced:
![picname0](https://user-images.githubusercontent.com/1939398/76074039-94879980-5f92-11ea-874f-a836dffdd5f0.jpg)
Then, to give the text a black background you can either put a rectangle behind it, which is rather complicated, or just make the font have a coloured background. That's what I will show here, but the issue is that the character sprites overlap so they need to be spread out again, making the text look a bit 'sparse':
![picname1](https://user-images.githubusercontent.com/1939398/76074394-31e2cd80-5f93-11ea-9175-37b127b966d4.jpg)
The position, size, rotation and justification can all be altered as in these different pictures. The location x=0,y=0 is in the middle of the screen with x increasing left to right, y increasing bottom to top. The width and height are attributes of DISPLAY. 
![picname2](https://user-images.githubusercontent.com/1939398/76074487-5474e680-5f93-11ea-99df-2267c4132278.jpg)
![picname3](https://user-images.githubusercontent.com/1939398/76074492-576fd700-5f93-11ea-9cb0-a3b38fe50180.jpg)
Let me know if you get stuck

**Comment by Ascendin81** [comment]
Wow, Thank you!.  I will get this working today after work.  Amazing!
